version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: ./server_tests